export const projects = [
   {
      id: 1,
      title: "Robo Sole",
      category: "UI/UX Design",
      description:
         "A futuristic design mock-up using Figma by a client request.",
      image: "/1.png",
      tech: ["Figma"],
      link: "https://www.figma.com/design/U4W0ZE9jRWKjl9HSaZPv3T/DESIGN-SAMPLES?node-id=123-30&p=f&t=SKKKzRFQffgkoAaZ-0",
   },
   {
      id: 2,
      title: "FitLife",
      category: "UI/UX Design",
      description: "A simple Fitness UI/UX Design.",
      image: "/2.png",
      tech: ["Figma"],
      link: "https://www.figma.com/design/U4W0ZE9jRWKjl9HSaZPv3T/DESIGN-SAMPLES?node-id=61-30&p=f&t=SKKKzRFQffgkoAaZ-0",
   },
   {
      id: 3,
      title: "Apex Vision",
      category: "UI/UX Design",
      description: "A minimalistic Sports Glass UI/UX Design.",
      image: "/3.png",
      tech: ["Figma"],
      link: "https://www.figma.com/design/U4W0ZE9jRWKjl9HSaZPv3T/DESIGN-SAMPLES?node-id=178-30&p=f&t=SKKKzRFQffgkoAaZ-0",
   },
   {
      id: 4,
      title: "1st Year Projects",
      category: "Web Application",
      description: "A compilation of my 1st Year Projects.",
      image: "/5.png",
      tech: ["HTML", "CSS", "JavaScript"],
      link: "https://github.com/carlotata/1st-Year",
   },
   {
      id: 5,
      title: "2nd Year Projects",
      category: "Web Application",
      description: "A compilation of my 2nd Year Projects.",
      image: "/4.png",
      tech: ["HTML", "CSS", "JavaScript"],
      link: "https://github.com/carlotata/2nd-Year",
   },
];
